### ISSUE TITLE
Strange behavior after ae9e752

### ISSUE THREAD

**Issue by illiliti** [rmyorston/pdpmake#13]
OK, i bisected the issue i described [here](https://github.com/rmyorston/pdpmake/pull/12#issuecomment-1159034503) to ae9e75231319a909bafab6ca43cae22449a6717e. After reverting that commit, everything back to normal.

Steps to reproduce:

```
$ make clean
$ make CFLAGS='-DENABLE_FEATURE_MAKE_EXTENSIONS=1'
...
$ ./make test
PASS: Basic makefile
PASS: .DEFAULT rule
PASS: Macro skipping in POSIX mode
PASS: Macro expansion and suffix substitution
PASS: Inference rule with explicit rule for prerequisite
SKIPPED: Double-colon rule
SKIPPED: Nested macro expansion in non-POSIX mode
SKIPPED: Chained inference rules
SKIPPED: Shell assignment
SKIPPED: Appending to simply-expanded macro
SKIPPED: Expand wildcards in filenames
SKIPPED: Basic pattern macro expansion
SKIPPED: Pattern macro expansion; match any value
SKIPPED: Pattern macro expansion with empty rvalue
SKIPPED: Pattern macro expansion with multiple <percent> in rvalue
SKIPPED: Pattern macro expansion; zero match
SKIPPED: Basic MAKE macro expansion
SKIPPED: MAKE macro expansion; overwrite with env macro
SKIPPED: MAKE macro expansion; overwrite with command-line macro
SKIPPED: MAKE macro expansion; turn relative path into absolute
SKIPPED: Compare $? and $^ internal macros
$ bmake test
PASS: Basic makefile
PASS: .DEFAULT rule
PASS: Macro skipping in POSIX mode
PASS: Macro expansion and suffix substitution
PASS: Inference rule with explicit rule for prerequisite
PASS: Double-colon rule
PASS: Nested macro expansion in non-POSIX mode
PASS: Chained inference rules
PASS: Shell assignment
PASS: Appending to simply-expanded macro
PASS: Expand wildcards in filenames
PASS: Basic pattern macro expansion
PASS: Pattern macro expansion; match any value
PASS: Pattern macro expansion with empty rvalue
PASS: Pattern macro expansion with multiple <percent> in rvalue
PASS: Pattern macro expansion; zero match
PASS: Basic MAKE macro expansion
PASS: MAKE macro expansion; overwrite with env macro
PASS: MAKE macro expansion; overwrite with command-line macro
PASS: MAKE macro expansion; turn relative path into absolute
PASS: Compare $? and $^ internal macros
```

**Comment by rmyorston** [comment]
If the binary was previously built with the default setting you'd need to do a ```make clean``` before running
>make CFLAGS='-DENABLE_FEATURE_MAKE_EXTENSIONS=1'

Just changing the define on the command line isn't enough to force a full rebuild.

**Comment by rmyorston** [comment]
Actually, I'm thinking of changing the default. Most of the time I want to build with extensions enabled anyway.

**Comment by illiliti** [comment]
> If the binary was previously built with the default setting you'd need to do a `make clean` before running
> 
> > make CFLAGS='-DENABLE_FEATURE_MAKE_EXTENSIONS=1'
> 
> Just changing the define on the command line isn't enough to force a full rebuild.

Yeah yeah i know this stuff. doesn't help.

**Comment by rmyorston** [comment]
From the commit message:
>In addition, if pdpmake is run with extensions enabled and a valid .POSIX special target is present, then PDPMAKE_POSIXLY_CORRECT is set in the environment.  Thus, recursive invocations of pdpmake will have non-POSIX features disabled.

Remove the ```.POSIX:``` from the makefile.

**Comment by illiliti** [comment]
> Remove the `.POSIX:` from the makefile.

Haha, truly "stepped on a rake" moment. Mind to push a fix since it's just a single-line change?

**Comment by rmyorston** [comment]
>Mind to push a fix since it's just a single-line change?

Will do.

**Comment by rmyorston** [comment]
I tried a different single-line change. The makefile is still declared POSIX-compliant.

**Comment by illiliti** [comment]
Works fine, thanks!
