### ISSUE TITLE
Implement $+ macro

### ISSUE THREAD

**Issue by illiliti** [rmyorston/pdpmake#19]
_The `$+` macro shall be equivalent to `$^`, except that duplicates shall not be removed; all prerequisites shall appear in the order they were listed in the makefile._

More info: https://www.austingroupbugs.net/view.php?id=514

**Comment by rmyorston** [comment]
```$+``` and ```$^``` are both now POSIX 202X features.

I see the Austin Group have been busy. Some other defect reports have been accepted.

Mostly these were already implemented as non-POSIX features so I'll just have to switch them to POSIX 202X. Expect more updates in due course.

**Comment by illiliti** [comment]
Nice, looking forward to them!
