### ISSUE TITLE
Are only files in `testsuite/` GPL licensed?

### ISSUE THREAD

**Issue by samboy** [rmyorston/pdpmake#20]
I observe this program is under two licenses, a public domain license in the top level directory, and a GPL license in the `testsuite/` directory. Since none of the programs in the top-level directory link to programs in the `testsuite/` directory, I presume it is **only** files in `testsuite/` that have the GPL license.

Please clarify this.

**Comment by rmyorston** [comment]
Your interpretation is correct. The make program is public domain (with a licence based on the [Unlicense](https://unlicense.org/)) and the testsuite is GPL. There's no link between the two, one just happens to live in a subdirectory of the other.

Shipping a binary based on the public domain code wouldn't result in any obligation under the GPL to provide the testsuite.

At least, that's _my_ interpretation, for what it's worth.

**Comment by samboy** [comment]
Thanks. Here’s my point of view, as someone with extensive professional programming experience: Ever since the SFLC lawsuits, the corporate reaction has not been for them to GPL or otherwise open source a bunch of code. The reaction has been to avoid anything with a GPL license whenever possible. I have run scanners which scan packages incorporating open source code to ensure that we were not using a single bit of GPL licensed code in our product.

Indeed, Apple has spent a lot of money getting LLVM and clang up to snuff so that they can have a compiler without needing to use GPL code, and will not distribute any GPL3 code with their products. Busybox has mostly been replaced with Toybox (which has everything major except `sh` and `awk`, both of which have non-GPL open source implementations)

Point being, there are a lot of use cases where a GPL license will stop people from using a given open source project, so I prefer not to have it in any code I may distribute. 

Thanks for reading my thoughts.  Closing ticket.
