### ISSUE TITLE
Should we make it possible to compile make without make?

### ISSUE THREAD

**Issue by samboy** [rmyorston/pdpmake#21]
Should we make it possible to compile `make` without `make`?

e.g.

```sh
#!/bin/sh

# This script has been donated to the public domain 2022 by Sam Trenholme

# A make implementation shouldn't need make to compile

if [ -z "$CC" ] ; then
  CC=cc
fi

if [ -z "$CFLAGS" ] ; then
  CFLAGS=-O2
fi

for a in *.c ; do
  echo $CC $CFLAGS -c -o ${a%.c}.o $a
  $CC $CFLAGS -c -o ${a%.c}.o $a
done

echo $CC $CFLAGS -o make *.o
$CC $CFLAGS -o make *.o
```

If so, I can submit a pull request.

**Comment by E5ten** [comment]
The first 2 parts for setting defaults can be rewritten as
```sh
: "${CC:=cc}" "${CFLAGS:=-O2}"
```
(or split into 2 lines if you think that looks cleaner).
This avoids the 2 calls to `test`, although in most shells `test` is a builtin anyway.

**Comment by samboy** [comment]
I just verified that the `: ${FOO:=bar}` syntax is a POSIX standard and not a Bashism: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18

**Comment by rmyorston** [comment]
Thanks for making a compile script!

I'm not sure it's really needed, though. Just ```cc -o make *.c``` is sufficient to bootstrap the binary.

**Comment by samboy** [comment]
> Just `cc -o make *.c` is sufficient to bootstrap the binary.

That should probably be documented in README.md.

**Comment by rmyorston** [comment]
>It might be a good idea to document this in README.md

OK, done that.
