### ISSUE TITLE
[Question] Does it support parallel make jobs?

### ISSUE THREAD

**Issue by tn1997tn** [rmyorston/pdpmake#26]
Both BSD make and GNU make support parallel make jobs.

**Comment by rmyorston** [comment]
`pdpmake` doesn't support parallel jobs. It has the `-j` command line option and the `.NOTPARALLEL` and `.WAIT` special targets. These are required by (draft future) POSIX. But the standard doesn't require implementations to do anything useful with them.

>Implementations that do not support parallelism can support the -j option by simply ignoring the option (other than passing it to sub-make invocations via the MAKEFLAGS environment variable).

**Comment by tn1997tn** [comment]
> `pdpmake` doesn't support parallel jobs. It has the `-j` command line option and the `.NOTPARALLEL` and `.WAIT` special targets. These are required by (draft future) POSIX. But the standard doesn't require implementations to do anything useful with them.
> 
> > Implementations that do not support parallelism can support the -j option by simply ignoring the option (other than passing it to sub-make invocations via the MAKEFLAGS environment variable).

The standard is useless as always. This is the reason why people all use GNU make.
