### ISSUE TITLE
lib(member.o) is POSIX

### ISSUE THREAD

**Issue by aabacchus** [rmyorston/pdpmake#27]
Possibly when this code was written it wasn't, but I don't think this syntax should be disabled in posix mode? (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html#tag_20_76_13_07)

https://github.com/rmyorston/pdpmake/blob/150207bb54baf94a9932d952c468b450f572e645/input.c#L1055-L1080

**Comment by rmyorston** [comment]
Yes, `lib(member.o)` is permitted by the standard. The code above is for the case where multiple members are specified in the brackets.

**Comment by rmyorston** [comment]
Or, at least, that was the intent. It might actually be wrong.

**Comment by aabacchus** [comment]
Ah... I probably quoted the wrong section of code. Still, I get "invalid target name" for `lib(member.o)` in POSIX mode.

**Comment by rmyorston** [comment]
OK, it looks as though the problem is with the check for valid characters in target names.

Obviously, to allow `lib(member.o)` as a target `(` and `)` have to be allowed. But they aren't.

**Comment by rmyorston** [comment]
>OK, it looks as though the problem is with the check for valid characters in target names.

The alternative view is that the check in the code is strictly correct: a conforming implementation _isn't_ required to support parentheses in target names.

On this view pdpmake is correct in rejecting `lib(member.o)` in POSIX mode.

Though it must be said this is contentious (#17)

**Comment by aabacchus** [comment]
Perhaps the standard should be read as target names have to only use the portable character set, but `lib(member.o)` is not a target name, it's a special syntax, and because `()` aren't permitted in target names, it's unambiguous.

**Comment by rmyorston** [comment]
OK, the standard does refer to `lib(member.o)` as an 'expression'. (Whatever that means: this is the only place the term is used.)

`lib` and `member.o` _are_ called 'names'.

I've updated the implementation reflect this interpretation.
