### ISSUE TITLE
Failed to process this makefile

### ISSUE THREAD

**Issue by iahunq** [rmyorston/pdpmake#28]
https://github.com/DragonFlyBSD/cpdup

`make -f GNUmakefile`

Error message:

```
c99 -O -pipe -std=c99 -pedantic -Wall -Wextra -Wlogical-op -Wshadow -Wformat=2  -Wwrite-strings -Wcast-qual -Wcast-align -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -o cpdup
gcc: fatal error: no input files
compilation terminated.
pdpmake: (GNUmakefile:37): failed to build 'cpdup'
```

**Comment by iahunq** [comment]
This version of `make` is too limited. I think I will stick with GNU make.

**Comment by chatchoi** [comment]
@rmyorston The current version of pdpmake failed with exactly the same error. It seems there is no progress on this. Why did the OP close this issue?
