### ISSUE TITLE
Unable to process the makefile of this project

### ISSUE THREAD

**Issue by iahunq2** [rmyorston/pdpmake#45]
The project I'm testing: https://github.com/objeck/objeck-lang

I'm using MSYS2 UCRT64. The build instruction is here:

https://github.com/objeck/objeck-lang/blob/master/core/readme.md

**Comment by rmyorston** [comment]
Can you be a bit more specific about the problem you're seeing? I have no wish to build such an enormous project on Windows (or indeed on any platform).

**Comment by iahunq2** [comment]
> Can you be a bit more specific about the problem you're seeing? I have no wish to build such an enormous project on Windows (or indeed on any platform).

This is the error message:

```
$ ./deploy_msys2-ucrt.sh
cd ../shared; make -f make/Makefile.msys2-ucrt.amd64 clean
rm -f *.o *~ sys.a
rm -f obc obc.exe *.o *.res *~
make: don't know how to make types.o
cp: cannot stat 'obc': No such file or directory
cd arch; make -f make/Makefile.msys2-ucrt.amd64 clean
rm -f *.o *~ ../memory.a
cd arch/jit/amd64; make -f make/Makefile.msys2-ucrt.amd64 clean
cd ..; make -f make/Makefile.msys2-ucrt.amd64 clean
rm -f *.o *~ amd64/jit_common.a
rm -f *.o *~ ../../../jit_amd_lp64.a
cd arch/win32; make -f make/Makefile.msys2-ucrt.amd64 clean
rm -f *.o *~ ../../win32.a
rm -f obr.exe obr *.exe *.dll *.o *~ *.res
make: don't know how to make common.o
cp: cannot stat 'obr': No such file or directory
cd ../vm/arch/win32; make -f make/Makefile.msys2-ucrt.amd64 clean
rm -f *.o *~ ../../win32.a
cd ../vm/arch/jit/amd64; make -f make/Makefile.msys2-ucrt.amd64 clean
cd ..; make -f make/Makefile.msys2-ucrt.amd64 clean
rm -f *.o *~ amd64/jit_common.a
rm -f *.o *~ ../../../jit_amd_lp64.a
cd ../vm/arch; make -f make/Makefile.msys2-ucrt.amd64 clean
rm -f *.o *~ ../memory.a
cd ../vm; make -f make/Makefile.msys2-ucrt.amd64.obd clean
cd arch; make clean -f make/Makefile.msys2-ucrt.amd64
make: no makefile found
make: (make/Makefile.msys2-ucrt.amd64.obd:22): failed to build 'clean' exit 2
make: (makefile:39): failed to build 'clean' exit 2
make: don't know how to make debugger.o
cp: cannot stat 'obd': No such file or directory
cd ../module; make -f make/Makefile.msys2-ucrt.amd64 clean
cd ../compiler; make -f make/Makefile.msys2-ucrt.amd64.mod clean
cd ../shared; make -f make/Makefile.amd64 clean
rm -f *.o *~ sys.a
rm -f compiler.a *.o *~
cd ../vm; make -f make/Makefile.msys2-ucrt.amd64.mod clean
cd arch; make clean -f make/Makefile.msys2-ucrt.amd64
make: no makefile found
make: (make/Makefile.msys2-ucrt.amd64.mod:28): failed to build 'clean' exit 2
make: (make/Makefile.msys2-ucrt.amd64:26): failed to build 'clean' exit 2
make: (makefile:20): failed to build 'clean' exit 2
make: don't know how to make editor.o
cp: cannot stat 'obi': No such file or directory
```

It stuck with a process of cc1plus running. I have to cancel with Ctrl + C.

**Comment by rmyorston** [comment]
This is odd:
```
cd arch; make clean -f make/Makefile.msys2-ucrt.amd64
make: no makefile found
make: (make/Makefile.msys2-ucrt.amd64.obd:22): failed to build 'clean' exit 2
make: (makefile:39): failed to build 'clean' exit 2
```
The command has the `clean` target before the `-f` option and `make` says `no makefile found` which suggests the `-f` wasn't processed and there's no default `Makefile` present.  Then the `clean` appears to fail.

Is your `make` binary built using MSYS2 and mingw64? It's possible there's something wrong with how `getopt(3)` is working here. And if it's wrong here it might cause problems elsewhere.

**Comment by iahunq2** [comment]
> Is your `make` binary built using MSYS2 and mingw64? It's possible there's something wrong with how `getopt(3)` is working here. And if it's wrong here it might cause problems elsewhere.

Since pdpmake requires POSIX functions it's impossible to build it with MinGW-w64. I built it on the MSYS Shell using the MSYS GCC (should be the same as the Cygwin GCC).

**Comment by rmyorston** [comment]
`make clean -f make/Makefile.msys2-ucrt.amd64` only works if the arguments are processed by the GNU C library implementation of `getopt(3)`. By default this moves all options to the start of the argument list. This isn't how `getopt(3)` is supposed to work, according to POSIX.

`getopt(3)` in MSYS2, like that in BSD, follows the standard.

I've altered argument processing in `pdpmake` to force GNU `getopt(3)` to follow the standard when POSIX compliance is being enforced.

This doesn't help with MSYS2 and the makefile in this project. The project is relying on the GNU C library behaviour, and it really shouldn't do that. Extending non-GNU `getopt(3)` to have the GNU behaviour is out of scope for `pdpmake`.

**Comment by chatchoi** [comment]
@rmyorston It seems the project has changed `make clean -f [makefile]` to `make -f [makefile] clean`. But `pdpmake` still fails with `don't know how to make [object file.o]` messages.
