### ISSUE TITLE
[QUESTION] Correct way to pass env vars?

### ISSUE THREAD

**Issue by ale5000-git** [rmyorston/pdpmake#58]
I have a problem: when using pdpmake the shell script correctly see the env var but when using GNU make the env var isn't set although it display the command correctly.

So is this way to set env vars not portable?

Example:

**./Makefile**
```
runscript:
	MY_CUSTOM_VAR=1 ./script.sh
```

**Comment by rmyorston** [comment]
Which GNU `make` are you using?

I can't reproduce this either. Both `mingw32-make.exe` from w64devkit and GNU `make` from MSYS2 print the value of the variable.

**Comment by ale5000-git** [comment]
It is:
```
GNU Make 4.3
Built for x86_64-pc-msys
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

It is the one bundled inside:
`ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]`

**Comment by rmyorston** [comment]
Sorry, I don't think I can help with that.

**Comment by ale5000-git** [comment]
Thank you all the same.
I will close it for now, I will write again in this ticket if I find a solution for this problem.

**Comment by ale5000-git** [comment]
I have found GNU Make 3.81 and it works, so the other was probably a broken one.
