### ISSUE TITLE
Test fails with MAKEFLAGS=-j4

### ISSUE THREAD

**Issue by dsan-dev** [rmyorston/pdpmake#60]
Hi.

When running `make test` with `MAKEFLAGS=-j4` in the environment (`export MAKEFLAGS=-j4`),
a test fails (Debian 12 using GNU Make 4.3).

This issue doesn't occur when running `make -j1 test` or `unset MAKEFLAGS && make test`.

Output of `make test`:

    PASS: Basic makefile
    ...
    FAIL: Macro skipping in POSIX 2017
    ...
    SKIPPED: Appending to immediate-expansion macro
    ...
    1 failure(s) detected; running with -v (verbose) will give more info
    make: *** [Makefile:27: test] Error 1

Output of `make -j1 test`:

    PASS: Basic makefile
    ...
    SKIPPED: Macro skipping in POSIX 2017
    ...
    PASS: Appending to immediate-expansion macro

**Comment by rmyorston** [comment]
`pdpmake` doesn't understand the `--jobserver-auth=3,4` option.

Clearing `MAKEFLAGS` in the main test script should do the trick. (It was already cleared in `make.tests`, but that was too late to avoid the problem.)
