### ISSUE TITLE
pdpmake can't handle this makefile

### ISSUE THREAD

**Issue by Curculigo** [rmyorston/pdpmake#62]
https://github.com/brechtsanders/pedeps/blob/master/Makefile

I'm using `busybox64.exe`.

**Comment by rmyorston** [comment]
The referenced Makefile uses a number of GNU `make` features which aren't supported by `pdpmake`.

A modified version which seems to work with `pdpmake` is: [Makefile.txt](https://github.com/user-attachments/files/16922967/Makefile.txt)

Translating Makefiles is sometimes entertaining, but it isn't a service I'll be providing as a matter of course.

**Comment by Curculigo** [comment]
> Translating Makefiles is sometimes entertaining, but it isn't a service I'll be providing as a matter of course.

It's only a bug report. If I really need help, I would ask directly like in my previous issue 😃

**Comment by mh466lfa** [comment]
> The referenced Makefile uses a number of GNU `make` features which aren't supported by `pdpmake`.

May I ask you which features?

**Comment by Curculigo** [comment]
`pdpmake` doesn't support the `shell` function. It also doesn't support multi-dotted file extensions. It doesn't support the `%.o: %.c` syntax, too. He has to replace it with `.c.o:`. This is what I have spotted so far. You can run `diff` against the original makefile and his modified makefile to see it more clear.

p/s: @rmyorston Please correct me if I'm wrong.

**Comment by rmyorston** [comment]
@Curculigo Yes, that just about covers it.

The `$(shell ...)` function calls have been replaced with the POSIX macro assignment `!=`.

There's also a `$(findstring ...)` function which was replaced with a `grep`. Indeed, _no_ GNU `make` functions of the form `$(function ...)` are supported by `pdpmake`.

Pattern rules like `%.o: %.c` were considered for standardisation by POSIX but they thought the changes required were too great. In this case they've been replaced with old-style suffix rules.
