### ISSUE TITLE
Can't handle this makefile

### ISSUE THREAD

**Issue by chatchoi** [rmyorston/pdpmake#66]
`pdpmake: (ScriptsLib/Makefile-Common.mk:10): expected separator`

https://github.com/SophistSolutions/Stroika/blob/v3-Release/Makefile

**Comment by rmyorston** [comment]
Line 10 of `ScriptsLib/Makefile-Common.mk` is:
```
export StroikaRoot
```
`export` is a GNU `make` feature which isn't supported in `pdpmake`.

Indeed, the very first line of the main Makefile also contains an unsupported GNU `make` feature:
```
StroikaRoot:=$(abspath .)/
```
Perhaps `pdpmake` should return an error for that.

**Comment by rmyorston** [comment]
>StroikaRoot:=$(abspath .)/
Perhaps pdpmake should return an error for that.

On reflection, no, it shouldn't. All implementations I've checked silently return an empty string when expanding a macro name that doesn't exist. Even if the name isn't a valid macro name.

POSIX 2024 says:
>... if the macro named by _string1_ does not exist, the final result shall be an empty string.

Clearly, if _string1_ isn't a valid macro name, no macro with that name can exist.

**Comment by chatchoi** [comment]
> Line 10 of `ScriptsLib/Makefile-Common.mk` is:
> 
> ```
> export StroikaRoot
> ```
> 
> `export` is a GNU `make` feature which isn't supported in `pdpmake`.

Now I know why it fails to process the makefile in #45. It has poor (or no support) of calling another instance of make recursively.

https://www.gnu.org/software/make/manual/html_node/Recursion.html

https://www.gnu.org/software/make/manual/html_node/Variables_002fRecursion.html

**Comment by chatchoi** [comment]
> > Line 10 of `ScriptsLib/Makefile-Common.mk` is:
> > ```
> > export StroikaRoot
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `export` is a GNU `make` feature which isn't supported in `pdpmake`.
> 
> Now I know why it fails to process the makefile in #45. It has poor (or no support) of calling another instance of make recursively.
> 
> https://www.gnu.org/software/make/manual/html_node/Recursion.html
> 
> https://www.gnu.org/software/make/manual/html_node/Variables_002fRecursion.html
> 
> Take this makefile as an example:
> 
> https://github.com/objeck/objeck-lang/blob/master/core/compiler/make/Makefile.msys2-ucrt.amd64.mod
> 
> The project in #45 is full of makefiles like this.

@rmyorston Please confirm if my conclusion is right or not. Thank you.

**Comment by rmyorston** [comment]
>Please confirm if my conclusion is right or not.

Sorry, I didn't try building this project.

The makefiles I've seen don't look too scary. I don't know what the actual problems are.
