### ISSUE TITLE
pdpmake: (pathext2.mak:7): expected separator

### ISSUE THREAD

**Issue by chatchoi** [rmyorston/pdpmake#67]
https://github.com/LADSoft/OrangeC/blob/master/src/pathext2.mak

**Comment by rmyorston** [comment]
The file `pathext2.mak` is incomplete. It's missing a line feed at the end of the last line.

When the file is fixed the error is correctly reported as
```
pdpmake: (pathext2.mak:8): expected separator
```

**Comment by Curculigo** [comment]
> `export` is a GNU `make` feature which isn't supported in `pdpmake`.

@chatchoi See #66.

**Comment by chatchoi** [comment]
> > `export` is a GNU `make` feature which isn't supported in `pdpmake`.
> 
> @chatchoi See #66.

OK. I added a new line in `pathext2.mak` and commented out all instances of `export` in `pathext2.mak` and `makefile`. Now I'm facing this nonsense:

```
pdpmake: can't open '#treetop.mak': No such file or directory
pdpmake: (makefile:67): failed to build 'tools' exit 1
```

Line 67 in `makefile`:

```
tools: 
	@$(MAKE) -f $(_TREEROOT) createdirs
	@$(MAKE) -f $(_TREEROOT) library
	@$(MAKE) -f $(_TREEROOT) exefile
```

It seems it's having problem correctly expanding `PATHEXT2`:

```
ifeq "$(PATHEXT2)" ""
ifeq "$(COMPILER)" "gcc-linux"
PATHEXT2 = /#
else
PATHEXT2 = \\#
endif
endif
#export PATHEXT2

```

If I removed `#` then it will fail with another nonsense:

```
pdpmake: (pathext2.mak:8): invalid conditional
```

**Comment by rmyorston** [comment]
@chatchoi The makefiles you're dealing with here (and in the other issues you've raised recently) were clearly written for GNU `make`.

`pdpmake` doesn't implement sufficient GNU `make` features to run them without serious changes, either to `pdpmake` or the makefiles.

If you need to run arbitrary makefiles that were written for GNU `make` your only realistic option is to use GNU `make`.

**Comment by rmyorston** [comment]
`PATHEXT2 = \\#`

As an extension, `pdpmake` allows '#' to be escaped with a backslash. In this case, though, it's the backslash which is being escaped with a second backslash, to avoid escaping the '#'.

This is the sort of subterfuge required to get a backslash into a macro.

Unfortunately, though, `pdpmake` doesn't support escaping backslashes.

Ho hum.
